import { BiUser,BiShoppingBag, BiStore, BiChip, BiCar, BiDollar } from "react-icons/bi";
import { BsFillBagFill } from "react-icons/bs";

export const projects = [
  {client:true,
    icon: BiShoppingBag,
    name: "Delight Tees",
    image:"/delight.jpg",
    homeDescription:"Custom e-commerce platform for premium apparel brand",
    projectCategory:"E-commerce",
    description: "Premium apparel brand specializing in custom-designed t-shirts and merchandise.",
    challenges:"Needed a modern e-commerce platform with inventory management, secure payments, and a seamless shopping experience.",
    solution:"Built a custom e-commerce platform with Stripe integration, real-time inventory tracking, order management dashboard, and responsive product catalog.",
    technologyStack:["Next.js", "Tailwind CSS", "PostgreSQL", "Stripe", "Cloudflare"],
    status:"ACTIVE",
    link:"/projects/delighttees",
  },
  {
    client:true,
    icon: BiUser,
    name: "Abia Women Assembly",
    image:"/awa.png",
    homeDescription:"Custom event registration and community management platform for Abia Women Assembly",
    projectCategory:"Non-Profit",
    description: "Official digital platform for Abia Women Assembly, providing seamless event registration, member management, and community engagement tools.",
    challenges:"Needed to streamline event registration and create a centralized platform for managing member information and community engagement.",
    solution:"Built a comprehensive platform with secure event registration, member directory, communication tools, and administrative dashboards.",
    technologyStack:["Next.js", "Tailwind CSS", "Supabase"],
    status:"ACTIVE",
    link:"/projects/abiawomenassembly",
  },
  {
    client:true,
    icon: BiStore,
    name: "Trendora Store",
    image:"/trendora.jpg",
    homeDescription:"Custom e-commerce platform for premium fashion brand",
    projectCategory:"Retail",
    description: "Fashion store offering trendy and affordable clothing for men and women.",
    challenges:"Needed a modern e-commerce platform with payment gateway integration, and a seamless shopping experience.",
    solution:"Built a custom e-commerce platform with payment gateway integration, and responsive product catalog.",
    technologyStack:["Next.js", "Tailwind CSS", "PostgreSQL", "Flutterwave", "Cloudinary"],
    status:"ACTIVE"
    },
  {
    client:true,
    icon: BsFillBagFill,
    name: "Meridian Crest Solutions",
    image:"/meridian.jpg",
    homeDescription:"Custom real estate development and property management company platform",
    projectCategory:"Corporate",
    description: "Real estate development and property management company",
    challenges:"",
    solution:"",
    technologyStack:["Next.js", "Tailwind CSS", "PostgreSQL", "Flutterwave", "Cloudinary"],
    status:"ACTIVE",
    link:"/projects/meridiancrestsolutions",
  },
  { 
    client:false,
    icon: BiChip,
    name: "AE Hub",
    image:"/aehubeco.jpg",
    homeDescription: "Internal platform powering our operations and partnerships",
    projectCategory:"Corporate",
    description: "Internal platform for project management, partnership coordination, and operational workflows. Centralizes client communications, project tracking, and resource allocation.",
    challenges:"",
    solution:"",
    technologyStack:["Next.js", "Tailwind CSS", "PostgreSQL", "Flutterwave", "Cloudinary"],
    status:"ACTIVE",
    key:[
      "Project pipeline management",
      "Partnership tracking",
      "Resource allocation",
      "Client communication hub",
      "Analytics dashboard"
    ],
    ecoshort:"The operational backbone of Agunwami Enterprise",
    ecodesc:"AE Hub is our flagship internal platform that powers project management, partnership coordination, and operational workflows. It serves as the central nervous system for all AE initiatives.",
    ecokey:["Project pipeline and milestone tracking","Partnership management and coordination","Resource allocation and planning","Client communication hub","Analytics and reporting", "Document management system"],
    link:"/projects/aehub",
    impact:"AE Hub has streamlined our operations, improved client communication, and enabled us to manage multiple projects simultaneously with transparency and efficiency."
  },
  { 
    client:false,
    icon: BiCar,
    name: "Mobility Platform",
    image:"/mobilityeco.jpg",
    homeDescription: "Transforming transportation and logistics in emerging markets",
    projectCategory:"Logistics",
    description: "A comprehensive platform designed to address mobility challenges in emerging markets. This system will connect drivers, riders, and logistics partners in a unified ecosystem.",
    technologyStack:["Next.js", "Tailwind CSS", "PostgreSQL", "Google Maps API"],
    status:"IN DEVELOPMENT",
    ecoshort:"Transforming transportation and logistics",
    ecodesc:"A comprehensive platform designed to address mobility challenges in emerging markets. This system will connect drivers, riders, and logistics partners in a unified ecosystem.",
    ecokey:["Real-time ride matching and tracking","Logistics and delivery management","Driver partner onboarding and management","Payment processing and settlement","Route optimization", "Safety and compliance monitoring"],
    link:"/projects/mobility",
    impact:"Expected to improve transportation accessibility, create economic opportunities for drivers, and streamline logistics operations across urban and rural areas."
  },
  { 
    client:false,
    icon: BiDollar,
    name: "Fintech Platform",
    image:"/fintecheco.jpg",
    homeDescription: "Financial infrastructure for underserved communities",
    projectCategory:"Fintech",
    description: "A digital financial services platform focused on providing accessible banking, payments, and financial tools to individuals and small businesses in emerging ecosystems.",
    technologyStack:["Next.js", "Tailwind CSS", "PostgreSQL", "Flutterwave", "Stripe"],
    status:"IN DEVELOPMENT",
    ecoshort:"Financial infrastructure for underserved communities",
    ecodesc:"A digital financial services platform focused on providing accessible banking, payments, and financial tools to individuals and small businesses in emerging ecosystems.",
    ecokey:["Digital wallet and mobile payments","Peer-to-peer transfers","Merchant payment solutions","Savings and credit products","Financial literacy resources", "Transaction analytics"],
    link:"/projects/fintech",
    impact:"Will increase financial inclusion, reduce transaction costs, and empower individuals and businesses with modern financial tools."
  },
];